title: Minnowbrook Logic Programming Seminar
description: "May 25 to May 28 · Upstate NY"
url: "https://minnowbrook.org"
theme: jekyll-theme-slate
minimal_mistakes_skin: mint
plugins:
  - jekyll-feed
  - jekyll-seo-tag
markdown: kramdown
permalink: pretty
collections: {}
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
include:
  - assets/css
sass:
  load_paths:
    - _sass
kramdown:
  input: GFM
  hard_wrap: false
